services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app        # Mount your code
      - db-data:/app  # Ensure SQLite file is persisted and writable
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db-data:
