# Generated by Django 5.1.6 on 2025-02-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentmodel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.coursemodel'),
            preserve_default=False,
        ),
    ]
